### ISSUE TITLE
Question about tail-invocation stack value length assertion (item 3)

### ISSUE THREAD

**Issue by jacobmischka** [WebAssembly/tail-call#10]
I'm reading through the spec, and https://github.com/WebAssembly/tail-call/blame/master/document/core/exec/instructions.rst#L1134 says that there must be at least `m` values on the stack, but then proceeds to pop `n` items from it

Should that `m` be `n`? Or am I misunderstanding something?

**Comment by rossberg** [comment]
That's a typo, the assertion should have said `n`. Fixed now.

**Comment by jacobmischka** [comment]
Thanks! Should the frame subscript here still be `m`? Or should that be `n` as well?

**Comment by rossberg** [comment]
No, that must match the return arity of the function called.
