### ISSUE TITLE
Question on design

### ISSUE THREAD

**Issue by serialhex** [WebAssembly/tail-call#13]
I think this is the best place to post this question, and if not, please direct me to where I should go.  My question is this: why add an instruction to enable properly optimized tail calls limited?  Why not just make all function calls able to be TCO'ed?  The only reason for this that I can think of is social in nature, not technical.  As in, most languages don't "need" TCO, and so don't have it.  This is like saying a language doesn't "need" structs/records to use adjacent pieces of memory, so your struct is a linked list.  In some ways easier to implement, but vastly slower in performance...

So really, is there a **good, technical** reason for separating it out into a separate instruction?  Or are we beholden to our Corporate OO Overlords?  It almost seems the latter, as TCO doesn't even have a base implementation in any browser as of yet... 😢 https://webassembly.org/roadmap/

**Comment by fgmccabe** [comment]
While TCO is considered an optimization in some languages; in others it is part of the semantics of the language. In any case, Wasm does not, in general, rely on in-engine optimizations. In that sense, Wasm is more like an assembler than a normal programming language.

return-call is implemented (behind a flag) in V8.

**Comment by serialhex** [comment]
But if it is an assembler, then why can't I do it?  AFAIK, I can do tail calls in X86 & ARM assembly without worrying about a stack explosion: https://en.wikipedia.org/wiki/Tail_call#In_assembly  And if it's not doing any in-engine optimizations, then why is something like "Bulk memory operations" a thing?  This seems very much like an in-engine optimization.

Also, Guy Steele argues **for** TCO in even OO languages that don't "need" it: http://www.eighty-twenty.org/2011/10/01/oo-tail-calls

**Comment by fgmccabe** [comment]
key phrase: "in general".
No argument about TCO in general. We are waiting for the process to complete. Note that the instructions will be called return_call and return_call_indirect.

**Comment by serialhex** [comment]
That still doesn't answer the question: is there a reason that `call` and `call_indirect` weren't changed to be TCO *instead* of *adding* TCO instructions?

The former seems like a much better and saner solution than adding instructions, especially if there is the potential of mixed code where half of it uses `return_call` and the other just `call` and odd behavior because of that?  Am I just overthinking it and it won't matter if WASM-Scheme code calls WASM-JS code back and forth?  I'm sure there's a non-pathological case where something like this would explode the stack when it shouldn't if there was only one TCO'ed call instruction.

**Comment by conrad-watt** [comment]
I think @fgmccabe's answer was clear: at Wasm's level of abstraction it's more appropriate for the resource cost of an instruction to be explicit, as far as is practicable. Consider that in the wikipedia page [you linked](https://en.wikipedia.org/wiki/Tail_call#In_assembly) the "tail call" at the platform assembly level is accomplished through different instruction selection (`jmp` instead of `ret`). This is what we're aiming for in Wasm too.

I feel your question is motivated by an assumption that dropping the separate instruction would get TCO into the Wasm ecosystem more quickly. I don't think this would work out, since engines need to do broadly the same implementation work either way.

**Comment by tlively** [comment]
To add to the previous answers, having separate instructions is important for putting TCO under the control of individual toolchains rather than leaving it up to engines. Consider a C++ compiler, for example, that can do either optimized builds or debug builds. In the optimized builds, the compiler will generate `return_call` and `return_call_indirect` instructions where appropriate, but in debug builds it will use `call` and `call_indirect` instead to make sure that all frames appear in backtraces. If there were not separate instructions for tail calls, it would be impossible (or at least more complicated) to satisfy both use cases with a single engine.

**Comment by lambda-fairy** [comment]
Yeah, I believe debuggability was why V8 refused to implement TCO for ES6. Safari/JavaScriptCore pulled it off with great effort using "shadow stacks", but AFAIK they're the only ones who managed to do it.

**Comment by rossberg** [comment]
@lambda-fairy, just for the record: V8 had fully implemented tail calls for ES6 by the same time JSC did. It was Mozilla and Microsoft who pulled the plug. The V8 team even proposed and prototyped an explicit variant called "syntactic tail calls" to save the feature, but to no avail. V8 removed tail calls when it was clear that the feature is dead.

**Comment by serialhex** [comment]
Sooooooo..... sounds pretty much like a political thing, and not a technological thing.  I seriously don't understand why a 40-year old and relatively easy optimization can't be put into a new VM, while significantly newer & more complicated optimizations I'm sure are being put in all over the place.  😞  It's stuff like this that makes me want to yeet most software devs into the Pacific ocean 😑 

I was thinking about finding the Firefox source, adding this, and making a PR, but I have the political clout of a dead snail...  😢

**Comment by rossberg** [comment]
Hm, I think multiple folks gave technical reasons upthread? You just disagree on their relevance.

**Comment by serialhex** [comment]
Not really no.  They are technical, but they are not reasons to not implement TCO.

The answer from conrad-watt here: https://github.com/WebAssembly/tail-call/issues/13#issuecomment-767078820 is close, but the resource cost of `return_call` the same or less than `call` (likewise for the `_indirect` variants).  So "knowing" the resource cost here is the same.

The answer from tlively here: https://github.com/WebAssembly/tail-call/issues/13#issuecomment-767114532 doesn't make sense because what about the frames for a `loop` in a backtrace?  If I loop from 0 to 2^128 are all those frames going to be in the backtrace?  What if I go through my array or linked list, are those frames?  A tree structure?  If not, then what is the difference if I'm using a recursive function to traverse a tree or array instead of a loop?  The answer is there is no difference, and your backtrace is just as useful (or useless) in both cases.  If you want that debugability then you need to remove loops from the language also, so you can get the backtrace from your loops to traverse your arrays.

So no, there doesn't seem to be an actual, good, technical reason for it.  You can debug just fine with TCO and the trace reflecting that (I've done it) and knowing that my recursive functions won't explode for any given input also helps me know what is going on in the computer.

**Comment by rpjohnst** [comment]
Here's another angle, then: Not every `call` is, can, or should be tail-call optimized. Further, and more importantly in this context, not even every *tail-position* `call` should be tail-call optimized: in a sense, `loop` (and eventually `return_call`) is *how you tell the VM* that you don't need a stack trace, and conversely `call` is how you tell the VM that you *do* need a stack trace.

This has one more important implication: In a world where the compiler specifically requests TCE from the VM, the VM can react predictably when TCE is impossible (e.g. with an error message, or by changing the semantics and making subsequent code dead).

If you instead conflate `call` and `return_call`, then you have very limited options for verifying that TCE actually takes place: either TCE becomes heuristic and implementations can vary, or the spec has to describe which `call`s are tail calls, which is another place for implementations to accidentally diverge. Nobody wants this.

Nobody here has any problem with providing TCE support in the VM. They just want an extra feature that you don't seem to care about- to encode whether a call is (meant to be) a tail call in the bytecode itself, just like you would in native assembly. At the end of the day, `call` and `return_call` *mean different things* at the machine level, and exposing that makes compilers and VMs simpler and more reliable- if this is political, it is only political in that it caters to more use cases than yours alone.

**Comment by serialhex** [comment]
Thank you @rpjohnst for pointing this out to me.  This does make sense, and I appreciate you (and everyone else in this thread) for helping me think through this.

I guess my main concern & thought was in dealing with languages where TCO is **required** (instead of simply where it would be beneficial).  I guess in my mind initially, in a theoretical WASM-scheme, every function call would use the `return_call` bytecode.  But now that I think about it with your insight, it should use `call` in the middle of a function, and `return_call` at the end...

Thank you @lambda-fairy 
Thank you @fgmccabe 
Thank you @rossberg 
Thank you @conrad-watt 
Thank you @tlively 

I appreciate each of your input, even if I initially disagreed with you.  Thank you.
